version: "3.9"
services:
    db_mysql:
        image: mysql
        container_name: ${DOCKER_PREFIX}_mysql_docker
        restart: always
        build: .docker/mysql
        ports:
            - "${DOCKER_MYSQL_PORT_3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
            MYSQL_USER: ${DOCKER_MYSQL_USER}
            MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
        networks:
            - dev

    php-apache:
        user: "0:0"
        build:
            context: .docker/php
            args:
                SERVER_NAME: ${DOCKER_APACHE_HOSTNAME}
        container_name: ${DOCKER_PREFIX}_www_docker
        ports:
            - "${DOCKER_APACHE_PORT_80}:80"
        volumes:
            - .:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:
        name: "dev"

volumes:
    app:

